### ISSUE TITLE
Add building ponyup images

### ISSUE THREAD

**Issue by SeanTAllen** [ponylang/ponyup#10]
We want:

- `latest` (we should discuss if we want to call this `master`)
- `release`
- `TAG` where `TAG` is something like `0.1.0` for each tagged release

We need to decide for all our applications where the images should be built. Autobuilds on dockerhub that are slow to get done or built on circleci which is much faster but requires a bit more configuration on our part.

**Comment by Theodus** [comment]
@SeanTAllen should be open up similar issues on our other application repos like stable/corral? This seems like it needs to be a more general discussion.

**Comment by SeanTAllen** [comment]
Discussed in zulip. Doing on circleci.

We do need to discuss latest vs master.

**Comment by SeanTAllen** [comment]
Partially addressed by #28
