### ISSUE TITLE
Add FreeBSD support

### ISSUE THREAD

**Issue by SeanTAllen** [ponylang/ponyup#101]
I believe this is mostly adding in order as we verify everything:

1- PR support for FreeBSD (including bootstrapping)
2- Nightly builds
3- Release builds

Because GitHub actions don't have FreeBSD support, we'll need to use CirrusCI.

**Comment by SeanTAllen** [comment]
Note... we can't do bootstrapping as part of the PR as it currently stands as it expects X number of things to be available and will fail

**Comment by Theodus** [comment]
Closed by #113
