### ISSUE TITLE
Support alternative Linux distributions

### ISSUE THREAD

**Issue by Theodus** [ponylang/ponyup#109]
such as [ponyc-x86-64-unknown-linux-ubuntu18.04](https://cloudsmith.io/~ponylang/repos/nightlies/packages/?q=ubuntu18.04)

**Comment by SeanTAllen** [comment]
@Theodus are you thinking that we hardcode the alternatives into ponyup and if a new alternative is added, then you have to update ponyc?

I'm thinking 3 options

1. list of alternatives is compiled into ponyup
2. list of alternatives is in a file that can be updated without updating ponyup
3. list of alternatives comes from querying cloudsmith

3. while momentarily appealing seems like a bad idea as the alternatives will show up forever even when we stop supporting them and want to remove

2. seems nice, but also a lot of extra work that might not be all that valuable anytime soon

1. seems like the best idea for us as long as adding new alternatives is straightforward.

**Comment by Theodus** [comment]
A list of target platforms for setting defaults would likely come from querying Clousmith, since that's how most things are done in ponyup. This issue is primarily concerned with making sure the code for parsing target triples is adapted to work with the new distros in the abi field.

**Comment by SeanTAllen** [comment]
Doesn't that mean that we are stuck with anything that ever goes in? That seems problematic.

**Comment by Theodus** [comment]
It can be filtered or ordered by version/date by default, with an option to show all available

**Comment by SeanTAllen** [comment]
So they could see for example that they can only get up to 0.28.0 and some nightly from the past? I guess that is a place to start and we can see how folks react to that.

**Comment by SeanTAllen** [comment]
@Theodus can this be closed?

**Comment by Theodus** [comment]
Yes
