### ISSUE TITLE
dyld: Library not loaded: /usr/local/opt/libressl/lib/libssl.47.dylib

### ISSUE THREAD

**Issue by aDotInTheVoid** [ponylang/ponyup#117]
Currently, brew installs `libcrypto.46.dylib` and`libssl.48.dylib`

However ponyup expects `libssl.47.dylib` and ` libcrypto.46.dylib`. This lead to errors like

```
dyld: Library not loaded: /usr/local/opt/libressl/lib/libssl.47.dylib
  Referenced from: /Users/nixon/.local/share/ponyup/bin/ponyup
  Reason: image not found
Abort trap: 6
```

**Comment by SeanTAllen** [comment]
@aDotInTheVoid which version of macOS are you using?

**Comment by SeanTAllen** [comment]
Also @aDotInTheVoid can you change this line in your ponyup-init.sh that you downloaded from "releases" to "nightlies" and let me know if you are good.

https://github.com/ponylang/ponyup/blob/master/ponyup-init.sh#L7

**Comment by aDotInTheVoid** [comment]
macOS Catilina: l10.15.4 (19E287)
libressl: stable 3.1.1 (bottled), HEAD [keg-only]

Unfortunately, nightly doesn't fix it

<details>
<summary> Full log</summary>

```bash
$ ./pony.sh
ponyup_root = /Users/nixon/.local/share/ponyup
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2905  100  2905    0     0   7830      0 --:--:-- --:--:-- --:--:--  7830
checksum=91cd9d02c4ed056f09d58c264e3abc2790ed9ae4543add06c473dd874cf13333
dl_url=https://dl.cloudsmith.io/public/ponylang/nightlies/raw/versions/20200513/ponyup-x86-64-apple-darwin.tar.gz
downloading ponyup-x86-64-apple-darwin.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  241k  100  241k    0     0  1155k      0 --:--:-- --:--:-- --:--:-- 1155k
checksum ok
ponyup placed in /Users/nixon/.local/share/ponyup/bin
$ which ponyup
/Users/nixon/.local/share/ponyup/bin/ponyup
$ ponyup
dyld: Library not loaded: /usr/local/opt/libressl/lib/libssl.47.dylib
  Referenced from: /Users/nixon/.local/share/ponyup/bin/ponyup
  Reason: image not found
Abort trap: 6
```
</details>

**Comment by SeanTAllen** [comment]
That's odd. I'm guessing that we need to do a brew update to get the latest package definitions. I'll set that up and ping you again in a couple days to test a nightly again.

Thanks for the information @aDotInTheVoid.

**Comment by SeanTAllen** [comment]
@aDotInTheVoid I got a little sidetracked. On Saturday Eastern US time, can you try the latest nightly and see if it works for you. It will be generated around midnight eastern time and will be ready anytime after that. I think will fix the issue as we should be linking against the latest libressl installed by homebrew at that point.

Thanks for your assistance!

**Comment by SeanTAllen** [comment]
@aDotInTheVoid scratch that. We have a chicken and the egg problem at the moment.

@Theodus I think we are going to have to install ponyc and corral "the hard way" on macOS in order to work around a dependency problem as we can't run ponyup to install corral with the updated libressl. I could get clever to get around that but I don't think that would help for long.

**Comment by SeanTAllen** [comment]
@Theodus to address this problem we need to make ponyup on macOS always install the most recent nightly rather than a release.

additionally, we need to tell people if they update libressl that they will need to reinstall the latest ponyup nightly IF brew installs the old ssl (I don't know if it does, that would be shitty, but, we'll find out).

**Comment by SeanTAllen** [comment]
@aDotInTheVoid can you try the latest nightly please?

**Comment by ergl** [comment]
@SeanTAllen had the same issue on Mojave 10.14.6, changing the default repository to "nightlies" fixed the issue for me.

**Comment by aDotInTheVoid** [comment]
Works for me with lates nightly too (`checksum=6143c010be7dcad9336d1d50735ff07d36104759b7c85d1b8e49a444ef47f9fe`)

Thanks for the fix
