### ISSUE TITLE
Enable select test for BSD

### ISSUE THREAD

**Issue by Theodus** [ponylang/ponyup#124]
The `select` test requires another release of ponyc with the `freebsd-12.1` versioning scheme. Once another release is out, remove the platform check in https://github.com/ponylang/ponyup/blob/81e3d7f94478637d1b1fa0c53dc6a89c49f71879/test/main.pony#L22

**Comment by SeanTAllen** [comment]
@Theodus so we can do this now, yes?

**Comment by Theodus** [comment]
I think so, yes
