### ISSUE TITLE
[macOS] error: unknown command at: 'platform'

### ISSUE THREAD

**Issue by Charlyzzz** [ponylang/ponyup#131]
Hey! 

Found out that there is no `ponyup platform` command as stated https://github.com/ponylang/ponyup/blob/d450da7a65749a0a09c53bb91bbedc296753c1a9/ponyup-init.sh#L221

Perhaps it's meant to say `ponyup default`?

**Comment by Theodus** [comment]
Thanks for reporting @Charlyzzz! A fix is on the way.
