### ISSUE TITLE
ponyc not installable on FreeBSD

### ISSUE THREAD

**Issue by Erk-** [ponylang/ponyup#160]
Trying to install `ponyc` on FreeBSD 12.1 fails with a error
```sh
(20:34:01 <~>) 0 $ ponyup default x86-64-unknown-freebsd-12.1
(20:40:44 <~>) 0 $ ponyup update ponyc release
error: unexpected selection: ponyc-release-x86-64-unknown-freebsd-12.1
```

I have also tried with other platform strings, though none seems to work.

**Comment by SeanTAllen** [comment]
@Theodus turning on the select test per #159 demonstrates that we indeed have a bug here. I also am working on a PR #161 to add bootstrap testing on FreeBSD 12.1.

**Comment by Theodus** [comment]
This should be resolved now. Sorry for the delay.
