### ISSUE TITLE
`ponyup update` from installation fails with "server unreachable"

### ISSUE THREAD

**Issue by EpicEric** [ponylang/ponyup#184]
Installing ponyup through the provided script and then running `ponyup update` fails as follows:

```sh
$ ponyup update ponyc release
updating ponyc-release-latest-x86_64-linux-gnu
syncing updates from https://api.cloudsmith.io/packages/ponylang/releases/
error: server unreachable, please try again later
```

Related commands that fetch data from Cloudsmith, such as `ponyup show`, also "fail" (exit code 0):

```sh
$ ponyup show -v
info: prefix: /home/eric/.local/share
info: platform: x86_64-unknown-linux-gnu
info: query url: https://api.cloudsmith.io/packages/ponylang/nightlies/?query=changelog-tool%20x86-64-unknown-linux%20status:completed&page=1&page_size=1
info: query url: https://api.cloudsmith.io/packages/ponylang/nightlies/?query=corral%20x86-64-unknown-linux%20status:completed&page=1&page_size=1
  [... snip ...]
info: query url: https://api.cloudsmith.io/packages/ponylang/releases/?query=stable%20x86-64-unknown-linux%20status:completed&page=1&page_size=1
error: server unreachable, please try again later
error: server unreachable, please try again later
  [... snip ...]
error: server unreachable, please try again later
ponyup-release-0.6.3-x86_64-linux
```

This seems to be ~related to OpenSSL 0.9.x being the default~ specific to the binary, since rebuilding `ponyup` ~with the flag `-Dopenssl_1.1.x`~ fixes this issue.

**Comment by SeanTAllen** [comment]
Seems like the issue was cloudsmith being down at the time.  So are you saying that something about 0.9 no longer works with cloudsmith?

**Comment by SeanTAllen** [comment]
@EpicEric I'm running with the version that uses 0.9.x and it works fine for me.

![image](https://user-images.githubusercontent.com/193596/113519639-7efcee80-955b-11eb-81e4-d6d60efabbd4.png)

**Comment by EpicEric** [comment]
> Seems like the issue was cloudsmith being down at the time. So are you saying that something about 0.9 no longer works with cloudsmith?

No, sorry. I meant that ponyup doesn't work if the machine has OpenSSL 1.1.x installed instead of 0.9.x:

```sh
# This command works fine
$ sh -c "$(curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/ponylang/ponyup/latest-release/ponyup-init.sh)"
 [... snip ...]
ponyup placed in /home/eric/.local/share/ponyup/bin
setting default platform to x86_64-unknown-linux-gnu

# Fails with status code 1
$ ponyup show
error: server unreachable, please try again later
error: server unreachable, please try again later
error: server unreachable, please try again later
error: server unreachable, please try again later
error: server unreachable, please try again later
error: server unreachable, please try again later
error: server unreachable, please try again later
error: server unreachable, please try again later
error: server unreachable, please try again later
error: server unreachable, please try again later
ponyup-release-0.6.3-x86_64-linux

# Build binary for OpenSSL 1.1.x instead
$ cd ~/git/ponyup && corral run -- ponyc -Dopenssl_1.1.x cmd -o ~/.local/share/ponyup/bin -b ponyup
 [... snip ...]

# Succeeds
$ ponyup show
ponyup-release-0.6.3-x86_64-linux

$ openssl version
OpenSSL 1.1.1d  10 Sep 2019
```

**Comment by SeanTAllen** [comment]
Ponyup is statically linked to ssl, it doesn't use your openssl.

**Comment by EpicEric** [comment]
You're right. Looking at the release scripts and running `ldd` on the binary, that seems to be the case. So this must be a different problem in action.

**Comment by SeanTAllen** [comment]
I don't have the issue, could be related to their CDN having issues near you perhaps?

**Comment by EpicEric** [comment]
While trying to reproduce this issue, I've discovered that it is related to a routing issue on my setup, unrelated to `ponyup`.
