### ISSUE TITLE
arm64 release

### ISSUE THREAD

**Issue by mfirry** [ponylang/ponyup#196]
Hi and sorry if this is already been asked.

When I run the `ponyup-init.sh` I get `Unsupported CPU type: arm64`.

I'm using a new Apple M1 ARM-based machine.

Thanks.

**Comment by SeanTAllen** [comment]
There's no arm64 support for ponyup at this time as we aren't doing any prebuilt binaries for any arm platforms at this time. If you have additional questions, stopping by the zulip might be best:

https://ponylang.zulipchat.com/

**Comment by mfirry** [comment]
Hi, something changed recentely I guess (just reading this https://twitter.com/ponylang/status/1455236810750238726)

**Comment by SeanTAllen** [comment]
There is still no ponyup support for m1. You still have to build from source.
