### ISSUE TITLE
Installation script fails on Asahi Linux

### ISSUE THREAD

**Issue by JONBRWN** [ponylang/ponyup#231]
when running the installation script via:
```
sh -c "$(curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/ponylang/ponyup/latest-release/ponyup-init.sh)"
```

The following error is returned:

```
Unsupported CPU type: aarch64
```

OS: Arch Linux ARM 5.17.0-rc7-asahi-next-20220310-5-1-ARCH
ponyc version: 0.49.1-cdd2e4d7

happy to dig into this if pointed in the right direction

**Comment by SeanTAllen** [comment]
There's currently no prebuilt aarch64 for Linux binaries, thus the error. 

All Linux support is x86. 

If you are interested in getting aarch64 Linux support working, stop by the CI stream on Zulip and let's chat about what would need to be done.
