### ISSUE TITLE
Improve output of show

### ISSUE THREAD

**Issue by Theodus** [ponylang/ponyup#24]
The `show` command output should be enhanced with the following:
1. Mark which of the installed packages are being used
2. List package versions available on Cloudsmith that have not been installed

**Comment by SeanTAllen** [comment]
@Theodus do we want to do this before the 0.2.0 release? I think it sounds like a good idea.

**Comment by Theodus** [comment]
Partially implemented in #45. I'm thinking that `show` should have an option to display the latest package on each channel. So only the most recent nightly and release versions for each package.
