### ISSUE TITLE
haven't macos amd64 apple-darwin in json

### ISSUE THREAD

**Issue by Angluca** [ponylang/ponyup#253]
Always download failed when I run 'sh ponyup-init.sh'

**Comment by SeanTAllen** [comment]
Please provide what you are getting for output?

**Comment by SeanTAllen** [comment]
Ah yes. We do not support amd64 anymore. You have to build from source to use amd64 for MacOS. See https://github.com/ponylang/ponyc/blob/main/BUILD.md

**Comment by SeanTAllen** [comment]
all pony ecosystem programs (corral, ponyc etc) need to build from source on amd64 MacOS. Start with ponyc, then you can build corral.
