### ISSUE TITLE
Error: missing subcommand at: 'ponyup'

### ISSUE THREAD

**Issue by bistace** [ponylang/ponyup#304]
Hello,

I am trying to install ponyc via ponyup but I am getting an error `Error: missing subcommand at 'ponyup'`. Here is the command that I am trying to run:
`ponyup update ponyc release`

Could you please help me solve this issue? I am on 64bit Ubuntu v22.04.

**Comment by mfelsche** [comment]
Which version of ponyup do you have installed on your machine (`ponyup version`)? What does `file $(which ponyup)` output for you?

Can you run your command above with verbose output like this: `ponyup -v update ponyc release` and copy the whole command you are trying to execute?

**Comment by bistace** [comment]
It seems that all I was missing was the package 'lsb-release'. Installing it with apt solved my problem. Thank you for taking the time to try and solve my problem and sorry for the inconvenience!

**Comment by bistace** [comment]
You are right. The first time I installed ponyup, I did not see that it complained that lsb-release was not found as there were some other logs around it. After uninstalling it to try again I saw the message, installed the lsb-release package and everything worked correctly after that!
