### ISSUE TITLE
ponyup-init.sh failing with "Illegal option -o pipefail"

### ISSUE THREAD

**Issue by RHagenson** [ponylang/ponyup#5]
It appears this is failing due to my distro linking `/bin/sh` to `dash`, which does not have the `pipefail` option. Necessary to proceed with an individual workaround or modify the init script itself to accommodate the lack of the option?

**Comment by SeanTAllen** [comment]
I think that instead of linking to /bin/sh, we should link to /bin/bash.

Thoughts @Theodus?

**Comment by Theodus** [comment]
@SeanTAllen I intend to test it with a POSIX shell once the builds are up and running. Until then the script does nothing useful
