### ISSUE TITLE
ArchLinux PKGBUILD for ponyup

### ISSUE THREAD

**Issue by superherointj** [ponylang/ponyup#54]
I've attempted to create an ArchLinux PKGBUILD for ponyup. It is working, installs "ponyup", sets up PATH, and ponyup is ready for use. But I'd like to receive feedback on it.

The goal was to be able to install `ponyup` by just doing `pacman -S ponyup`. And having a cleaner system because on uninstalling pacman automatically removes all the installed package files.

Repository: 
[https://github.com/superherointj/arch-pkgbuild-ponyup](https://github.com/superherointj/arch-pkgbuild-ponyup)

Problems/Questions:

1 - Is distribution packaging of "ponyup" (for Arch Linux) welcomed? Is there a philosophical problem between installing 'ponyup' using a script or pacman?
2 - Can I refer to "ponyup" as PonyUp?
3 - I had trouble using "make" (lack of cc error, or linker) so I used pony compiler directly. With `-pic` directive. It has worked for me. But Is it fine? Can I keep this way?

> stable fetch && stable env ponyc --pic -Dopenssl_1.1.x -o ./build/ -b ponyup cmd

4 - I had to workaround `cmd/version.pony` need, so I manually did:

>    printf 'primitive Version\n  fun apply() : String =>\n    "%s"' "$pkgver" > cmd/version.pony

5 - Any other consideration?

This package probable can improved further and I'd appreciate if you have any feedback on it.

Thanks.

**Comment by SeanTAllen** [comment]
> Is distribution packaging of "ponyup" (for Arch Linux) welcomed?

YES! This is awesome.

>  Is there a philosophical problem between installing 'ponyup' using a script or pacman?

Not sure what you mean, if you would like to maintain a way to do it with pacman, then have at it!

> Can I refer to "ponyup" as PonyUp?

well, the name of the command is ponyup and we refer to it as such. @Theodus I think we want to keep it as ponyup. Do you have an opinion?

> I had trouble using "make" (lack of cc error, or linker) so I used pony compiler directly. With -pic directive. It has worked for me. But Is it fine? Can I keep this way?

It's on you to maintain it. However, I think this is a bad idea and you should using make. It will make maintenance much much easier. 

Here's something to consider. Nightly and release builds are created and stored in cloudsmith, you might be able to use those.

I don't know anything about pacman, so, you are the expert. As long as everything works, then that is what is important. I think you should aim to use the supplied build system as it will save you a lot of pain down the road, but... again, it's your project and you are maintaining it.

**Comment by Theodus** [comment]
> Can I refer to "ponyup" as PonyUp?

I think it should remain "ponyup".

**Comment by superherointj** [comment]
Glad to know packaging ponyup for ArchLinux is welcomed.
  
The AUR team advised me to build ponyup from sources instead of downloading binaries.
ArchLinux AUR requires compiling from sources and does not allow downloading or running a script that downloads and runs remote files for security reasons. PKGBUILD has to follow the ArchLinux AUR philosophy. In this case, ponyup-init.sh is unfit. The PKGBUILD will do the same function ponyup-init.sh does, and will replace it.

I did not mean to suggest any change to application name. Just wanted to confirm how the application should be written. "ponyup" is the name, everything in lower case, no uppercase.

I acknowledge the value of using same build system. I will make another attempt to use
 the Makefile. And I'll report back my findings, so please, for now, leave this issue
open. I'm still working on this.

Pacman is a really nice package manager. One day give it/Arch a try. You might find yourself loving it. :)

**Comment by SeanTAllen** [comment]
@superherointj shall we keep this issue open or is it good to close now?

**Comment by superherointj** [comment]
ponyup is available at ArchLinux's AUR.
https://aur.archlinux.org/packages/ponyup/
Arch users can:
`yay -S ponyup`
And eventually, hopefully (not available yet): pacman -S ponyup

Used make as suggested, removed the version crap thing, seems better:
https://github.com/superherointj/arch-pkgbuild-ponyup/blob/master/PKGBUILD

Great day!
