### ISSUE TITLE
Add macOS support

### ISSUE THREAD

**Issue by SeanTAllen** [ponylang/ponyup#55]
We now have nightly ponyc builds going into Cloudsmith. (x86-64-apple-darwin). The time is right to add Ponyup support for macOS. This will make control over releases much easier as we won't be relying on a 3rd party distribution tool like homebrew.

**Comment by Theodus** [comment]
Tracking for [macos branch](https://github.com/ponylang/ponyup/tree/macos)
- [x] Allow Darwin in `ponyup-init.sh`
- [ ] Specify platform OS in `package.pony`
- [ ] Build nightly releases of ponyup for macOS
- [ ] Setup CI for macOS

**Comment by SeanTAllen** [comment]
@Theodus I added nightly and release build to the `macos` branch.

**Comment by SeanTAllen** [comment]
@Theodus CI for macOS is setup on the `macos` branch. It runs the bootstrap script as well as `make test`. Please update as you see fit.
