### ISSUE TITLE
Remove temporary musl script and ifdefs for macOS tests

### ISSUE THREAD

**Issue by Theodus** [ponylang/ponyup#61]
https://github.com/ponylang/ponyup/pull/60#issuecomment-569762164

**Comment by SeanTAllen** [comment]
What are the criteria for when the `ifdefs` can be removed? 2 macOS releases?

**Comment by Theodus** [comment]
1 or more releases will allow the tests to pass. The sync tests select up to the 2 most recent for each package.

**Comment by Theodus** [comment]
MacOS test ifdefs removed in #91
Temporary musl script removed in #63
