### ISSUE TITLE
Add Windows support

### ISSUE THREAD

**Issue by SeanTAllen** [ponylang/ponyup#62]
Ponyup should work on Windows. 

As part of this, I think we want to move from our current Makefile to something CMake based that can support all platforms (like we are currently doing with ponyc).

@kulibali I'm going to ping you about what a switch to Cmake would entail.

**Comment by SeanTAllen** [comment]
Symlinking on Windows requires you to have admin-level privileges. In order to support Windows, we will want to replace (on Windows only) the usage of symlinks with copying the binaries in question.

**Comment by SeanTAllen** [comment]
@kulibali this feels like an important step towards getting all our major platforms normalize in how we install etc. are you feeling up to taking this one on?

**Comment by kulibali** [comment]
Yeah it's next on my list.

**Comment by SeanTAllen** [comment]
Kulibali has implemented this.
