### ISSUE TITLE
On uninstalling ponyup should ".local/shared/ponyup" be deleted?

### ISSUE THREAD

**Issue by superherointj** [ponylang/ponyup#87]
As I have packaged ponyup for Arch Linux, on uninstalling ponyup, should ".local/shared/ponyup" be deleted?

**Comment by SeanTAllen** [comment]
I don't think this is a ponyup issue. I think this is an Arch packaging issue. I would suggest you investigate what other Arch packages do and conform to the expectations that Arch users might have.

**Comment by superherointj** [comment]
Ok, thanks.
